//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpoMaker.resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQL_Statements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQL_Statements() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EpoMaker.resources.SQL_Statements", typeof(SQL_Statements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DELETE FROM &apos;{0}&apos;; ähnelt.
        /// </summary>
        internal static string Clear_CourseMembers {
            get {
                return ResourceManager.GetString("Clear_CourseMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CREATE TABLE &apos;{0}-Data&apos; (&apos;schuelerID&apos;INTEGER,&apos;Note&apos;	REAL,&apos;Stunde&apos;date,&apos;Fehlt&apos;BOOLEAN,&apos;Doppelstunde&apos;BOOLEAN,FOREIGN KEY(&apos;schuelerID&apos;) REFERENCES &apos;{0}&apos;(&apos;schuelerID&apos;)); ähnelt.
        /// </summary>
        internal static string Create_Course_Data_Table {
            get {
                return ResourceManager.GetString("Create_Course-Data_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CREATE TABLE &apos;{0}&apos; (&apos;schuelerID&apos;INTEGER,&apos;Vorname&apos;TEXT,&apos;Nachname&apos;TEXT,PRIMARY KEY(&apos;schuelerID&apos;)); ähnelt.
        /// </summary>
        internal static string Create_Course_Table {
            get {
                return ResourceManager.GetString("Create_Course_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CREATE TABLE &apos;TableList&apos; (&apos;Name&apos;TEXT,&apos;CurrentPos&apos;INTEGER,PRIMARY KEY(&apos;Name&apos;)); ähnelt.
        /// </summary>
        internal static string Create_TableList_Table {
            get {
                return ResourceManager.GetString("Create_TableList_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SELECT * FROM &apos;{0}&apos;; ähnelt.
        /// </summary>
        internal static string Get_All {
            get {
                return ResourceManager.GetString("Get_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SELECT DISTINCT Stunde From &apos;{0}-Data&apos; ORDER By Stunde ASC; ähnelt.
        /// </summary>
        internal static string Get_All_Lessons {
            get {
                return ResourceManager.GetString("Get_All_Lessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SELECT Stunde,Note From &apos;{0}-Data&apos; WHERE schuelerID={1} AND Fehlt=&apos;False&apos; ORDER By Stunde ASC; ähnelt.
        /// </summary>
        internal static string Get_All_Student_Grades {
            get {
                return ResourceManager.GetString("Get_All_Student_Grades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SELECT Nachname,Vorname,schuelerID From &apos;{0}&apos;; ähnelt.
        /// </summary>
        internal static string Get_Course_Persons {
            get {
                return ResourceManager.GetString("Get_Course_Persons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SELECT CurrentPos FROM TableList WHERE Name=&apos;{0}&apos;; ähnelt.
        /// </summary>
        internal static string Get_CurrentPos {
            get {
                return ResourceManager.GetString("Get_CurrentPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SELECT SUM(CASE WHEN Doppelstunde=&apos;True&apos; THEN Note*2 ELSE Note END)/(SUM(Case WHEN Doppelstunde=&apos;True&apos; THEN 1 ELSE 0 END)+count(Note)) as Durchschnitt FROM &apos;{0}-Data&apos; Where schuelerId={1} AND Fehlt=&apos;False&apos;; ähnelt.
        /// </summary>
        internal static string Get_Single_Student_Grade_Average {
            get {
                return ResourceManager.GetString("Get_Single_Student_Grade_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert INTO TableList (Name) Values (&apos;{0}&apos;); ähnelt.
        /// </summary>
        internal static string Insert_Course_To_TableList {
            get {
                return ResourceManager.GetString("Insert_Course_To_TableList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die INSERT INTO &apos;{0}&apos;(schuelerID,Vorname,Nachname) VALUES ({1},&apos;{2}&apos;,&apos;{3}&apos;); ähnelt.
        /// </summary>
        internal static string Insert_Users_To_Course {
            get {
                return ResourceManager.GetString("Insert_Users_To_Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ALTER TABLE &apos;{0}&apos; RENAME TO &apos;&apos;{1}&apos;; 
        ///ALTER TABLE &apos;&apos;{0}-Data&apos; RENAME TO &apos;&apos;{1}-Data&apos;; 
        ///UPDATE TableList SET Name=&apos;&apos;{1}&apos; WHERE Name=&apos;&apos;{0}&apos;; ähnelt.
        /// </summary>
        internal static string Rename_Course {
            get {
                return ResourceManager.GetString("Rename_Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UPDATE &apos;TableList&apos; SET CurrentPos={1} WHERE Name=&apos;{0}&apos;; ähnelt.
        /// </summary>
        internal static string Set_CurrentPos {
            get {
                return ResourceManager.GetString("Set_CurrentPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die INSERT INTO &apos;{0}-Data&apos;(&apos;schuelerID&apos;,&apos;Note&apos;,&apos;Stunde&apos;,&apos;Fehlt&apos;,&apos;Doppelstunde&apos;) VALUES ({1},&apos;{2}&apos;,&apos;{3}&apos;,&apos;{4}&apos;,&apos;{5}&apos;); ähnelt.
        /// </summary>
        internal static string Set_Note_Data {
            get {
                return ResourceManager.GetString("Set_Note_Data", resourceCulture);
            }
        }
    }
}
